#version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: php_apache
    ports:
      - "80:80"
    volumes:
      - ./php_Code:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user1
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mydbdata: /backup 

volumes:
  mydbdata:
