version: '3.8'

services:
  db:
    image: nouchka/sqlite3
    volumes:
      - chatroom_data:/data

  server:
    build:
      context: .
      dockerfile: Dockerfile.server 
    ports:
      - "1234:1234"
    depends_on:
      - db
    environment:
      - DATABASE_PATH=/data/users.db
    volumes:
      - chatroom_data:/data

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server

volumes:
  chatroom_data:
